# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ qa, master ]
  pull_request:
    branches: [ qa, master ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: finish

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setting up Kubernetes
      run: | 
        sudo mount --make-rshared /
        curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
        chmod +x kubectl
        sudo ln -s $(pwd)/kubectl /usr/local/bin/kubectl
        wget https://github.com/kubernetes/minikube/releases/download/v0.28.2/minikube-linux-amd64 -q -O minikube
        chmod +x minikube
        sudo ln -s $(pwd)/minikube /usr/local/bin/minikube
        sudo minikube start --vm-driver=none --bootstrapper=localkube
    - name: Run Test
      run: chmod +x ../scripts/travisTest.sh && ../scripts/travisTest.sh
